---
title: "1-29 final macros"
author: "Ryan Goluch"
date: "1/29/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#The macro for calculating manufacturing percentages
#No data table output code
#Youth in manufacturing included in percentages

empl <- read.csv("Data/employment.csv")

empl$State <- empl$State.Territory
empl$women_manufacturing <- 100*(empl$FEMALES.ABOVE.AGE.16.EMPLOYED.IN.MANUFACTURING/empl$TOTAL.HANDS.EMPLOYED.IN.MANUFACTURING)
empl$men_manufacturing <- 100*(empl$MALES.ABOVE.AGE.16.EMPLOYED.IN.MANUFACTURING/empl$TOTAL.HANDS.EMPLOYED.IN.MANUFACTURING)
empl$youth_manufacturing <- 100*(empl$YOUTHS.EMPLOYED.IN.MANUFACTURING/empl$TOTAL.HANDS.EMPLOYED.IN.MANUFACTURING)
empl$percent_manufacturing <- 100*(empl$TOTAL.HANDS.EMPLOYED.IN.MANUFACTURING/empl$TOTAL.POPULATION)

c(empl$State, empl$women_manufacturing, empl$men_manfucaturing, empl$youth_manufacturing, empl$percent_manufacturing)

```

```{r}
#The macro for calculating school attendance percentages
#No data table output code 

empl <- read.csv("Data/employment.csv")

empl$State <- empl$State.Territory
empl$women_school <- 100*((empl$WHITE.FEMALES.ATTENDING.SCHOOL+empl$COLORED.FEMALES.ATTENDING.SCHOOL)/empl$TOTAL.PERSONS.ATTENDING.SCHOOL)
empl$men_school <- 100*((empl$WHITE.MALES.ATTENDING.SCHOOL+empl$COLORED.MALES.ATTENDING.SCHOOL)/empl$TOTAL.PERSONS.ATTENDING.SCHOOL)
empl$percent_school <- 100*(empl$TOTAL.PERSONS.ATTENDING.SCHOOL/empl$TOTAL.POPULATION)

c(empl$State, empl$women_school, empl$men_school, empl$percent_school)

```